### ISSUE TITLE
CSF/SC contrast figure does not have the same y-scale

### ISSUE THREAD

**Issue by dpapp86** [shimming-toolbox/rf-shimming-7t#101] opened 2024-05-21 17:39 UTC
Hello!

@agahkarakuzu @mathieuboudreau @jcohenadad 

I do not know when this happened, but in the updated figure 4 in the draft text, the y-scale is correctly set to be the same for all five subjects, same with the B1+ efficiency

<img width="717" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/e2276687-702b-4258-87bf-4ef32acf7095">

However, as of this PR: #100, this is no longer the case.

<img width="1106" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/80138067/d169d437-f8b1-40b5-9f7c-cebfafda0ad8">

**Comment by mathieuboudreau** [comment] 2024-05-21 18:43
I think I had only set the fixed y-scale for the matplotlib plots (first images you show), but not the plotly images (second set). The reason being the plotly images were not the ones used for the manuscript submission, I don't recall the reason but that was Julien's request in one of these threads.

This was the PR where I merged that feature: https://github.com/shimming-toolbox/rf-shimming-7t/commit/63eba66e3bbac888864ad63e93eb8f9ccba12ec5

So if those lines are not there, we would just need to reintroduce them

**Comment by mathieuboudreau** [comment] 2024-05-21 18:44
ps. to actually view the diff, the [nbdime](https://nbdime.readthedocs.io/en/latest/) tool is best suited for jupyter notebook diffs

**Comment by dpapp86** [comment] 2024-05-24 09:26
Ah.

Sorry to bother you again, @agahkarakuzu. Looking at the notes in the paper, we want CSF/SC ratio to be Figure B, and B1+ ratio to be Figure A. Can you please swap?

**Comment by dpapp86** [comment] 2024-05-26 18:01
@agahkarakuzu gentle ping

Thank you!

**Comment by agahkarakuzu** [comment] 2024-05-26 22:13
@dpapp86 I tore down binderhub deployments for maintenance, and that's the only place I can confirm my changes work.

I'll try to get to this on Monday.

**Comment by jcohenadad** [comment] 2024-05-27 12:14
the A and B should be translated slighty towards the bottom, such that the bottom of each letter aligns with the bottom of the x-label

**Comment by agahkarakuzu** [comment] 2024-05-27 12:24
I've been editing the interactive version btw, is that the one you were referring?

**Comment by jcohenadad** [comment] 2024-05-27 12:58
i’m referring to the static image above my post that will be used for the MRM submission (last missing piece before we can resubmit)

**Comment by agahkarakuzu** [comment] 2024-05-27 13:01
FYI those are screenshots of the plotly figure, I'll push the edits you want and will share a highres png if you'd like to go with those.

**Comment by mathieuboudreau** [comment] 2024-05-27 13:24
> FYI those are screenshots of the plotly figure, I'll push the edits you want and will share a highres png if you'd like to go with those.

I think in the initial submission, it's not the plotly figures that were included in the MRM submission but the matplotlib ones that are above it. That's the reason why I had to reintroduce them: https://github.com/shimming-toolbox/rf-shimming-7t/commit/208b1e80ddfd1f4313b649c67c5d07d711a47ae7

**Comment by mathieuboudreau** [comment] 2024-05-27 13:25
@agahkarakuzu let me know if you'd like me to retake this over - no matter to me!

**Comment by agahkarakuzu** [comment] 2024-05-27 13:33
![custom_image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/9632322/9466e767-bb13-468b-bb49-f19fc64a3728)

@mathieuboudreau I've just pushed the changes @jcohenadad requested to `agah-patch1` branch for which this PR was created. If there's anything else, feel free to take on as I think it would be more efficient! 

<img width="456" alt="image" src="https://github.com/shimming-toolbox/rf-shimming-7t/assets/9632322/4bcbf05c-030f-4720-b834-37a345bcad54">

**Comment by jcohenadad** [comment] 2024-05-27 13:59
![image](https://github.com/shimming-toolbox/rf-shimming-7t/assets/2482071/85945122-0c94-46e0-9d1f-82749201630e)

placement is perfect, but the fonts should be black (they seem dark grey) to be consistent throughout the manuscript

**Comment by mathieuboudreau** [comment] 2024-05-27 14:03
On it

**Comment by jcohenadad** [comment] 2024-05-27 14:05
@mathieuboudreau since you read this notif-- pls invite me to the ADS meeting-- urgent-- thx

**Comment by mathieuboudreau** [comment] 2024-05-27 15:08
![custom_image-42](https://github.com/shimming-toolbox/rf-shimming-7t/assets/1421029/0bcaccc8-dbca-4b1f-993d-48c2b13f48a1)

Here's the latest figure - happy to do more changes if needed

**Comment by jcohenadad** [comment] 2024-05-27 15:18
thank you @mathieuboudreau -- sorry for the nitpick but the A and B should be translated slightly, such that the bottom of each letter aligns with the bottom of the x-label (Vertebral Levels), and the left side of "A" aligns with the top side of the y-label.

**Comment by jcohenadad** [comment] 2024-05-27 15:21
another nitpick: would it be possible to use Arial font (to be consistent throughought the manuscript)

**Comment by mathieuboudreau** [comment] 2024-05-27 15:23
No problem! Brb

**Comment by mathieuboudreau** [comment] 2024-05-27 16:25
@jcohenadad Here's the latest version:

![custom_image-48](https://github.com/shimming-toolbox/rf-shimming-7t/assets/1421029/1e0bd3ee-00b8-4f6b-a028-4e390a8f6ce7)

**Comment by jcohenadad** [comment] 2024-05-27 17:20
amazing, can you please make the legend font slightly bigger?
also, if not complicated, close the box on right and top
thanks!

**Comment by mathieuboudreau** [comment] 2024-05-27 18:47
@jcohenadad Here's the newest version!

![custom_image-49](https://github.com/shimming-toolbox/rf-shimming-7t/assets/1421029/2e5b005b-a1e4-4586-b469-4cf2133a570b)

**Comment by jcohenadad** [comment] 2024-05-27 18:55
- the legend is overlaying quite a large part of 'useful' information-- would it be possible to shift it towards the bottom left side of the figure axis (where there is less curves)
- possible to slightly increase the size of the other labels (x-lab, y-lab, and axis lab), maybe use the same size as the legend for consistency
thx!

**Comment by mathieuboudreau** [comment] 2024-05-27 19:28
Here's the update!

![custom_image-52](https://github.com/shimming-toolbox/rf-shimming-7t/assets/1421029/4cf37346-5234-47b8-8918-000dee5bfb27)

**Comment by jcohenadad** [comment] 2024-05-27 19:30
that's a winner! thank you for your patience

**Comment by mathieuboudreau** [comment] 2024-05-27 19:30
No problem! I'll upload it to the paper's folder now and update the manuscript

**Comment by mathieuboudreau** [comment] 2024-05-27 19:36
Done! @agahkarakuzu I've pushed all my changes to the branch you were working on (agah-patch1), should we merge now?

**Comment by dpapp86** [comment] 2024-05-28 14:44
@agahkarakuzu @mathieuboudreau Please merge ASAP, we need to submit the revised paper ASAP, and we want to include an up to date link for the proper version.

Please ping Julien when you have merged

**Comment by agahkarakuzu** [comment] 2024-05-28 15:57
Oh I see sorry, I thought you were mentioning the version on neurolibre. 

I am lost here a bit too given that I am not actually a part of this, but if what's needed is a release, I can do that.

**Comment by mathieuboudreau** [comment] 2024-05-28 16:18
>I am lost here a bit too given that I am not actually a part of this, but if what's needed is a release, I can do that.

Let me merge and make the release; we need to update the link where the badges point on the README, and provide the version link for the paper. I'll update here when I'm done.

As agah mentionned, the neurolibre version / link can't be updated (it's a preprint, so only for the version prior to the initial submission).

**Comment by mathieuboudreau** [comment] 2024-05-28 16:28
Published the release (https://github.com/shimming-toolbox/rf-shimming-7t/releases/tag/r20240428), now checking that the notebook executes on Colab since Agah and I were developing for the PRs on the NeuroLibre servers, brb

**Comment by jcohenadad** [comment] 2024-05-28 16:29
should be 20240528 no?

**Comment by mathieuboudreau** [comment] 2024-05-28 16:29
Woops, yes you're right I got the month wrong, my bad. Fixing it

**Comment by mathieuboudreau** [comment] 2024-05-28 16:52
Here's the release version: https://github.com/shimming-toolbox/rf-shimming-7t/releases/tag/r20240528

Here's the link to the actual code for that version: https://github.com/shimming-toolbox/rf-shimming-7t/tree/r20240528

Here's the link to Google Colab for that version: https://colab.research.google.com/github/shimming-toolbox/rf-shimming-7t/blob/r20240528/content/index.ipynb

**Comment by mathieuboudreau** [comment] 2024-05-28 16:54
Anything else needed / any other links? This is the NeuroLibre stuff as a reminder (but points to the original preprint)

DOI: https://doi.org/10.55458/neurolibre.00025
Interactive Preprint: https://preprint.neurolibre.org/10.55458/neurolibre.00025/
NeuroLibre Binder server link for that version: https://binder-mcgill.conp.cloud/v2/gh/roboneurolibre/rf-shimming-7t/main?urlpath=lab/tree/content/index.ipynb

**Comment by dpapp86** [comment] 2024-05-28 16:55
A thousand blessings on your house!

Pinging @jcohenadad

**Comment by jcohenadad** [comment] 2024-05-28 16:58
amazing! thank you SOOO much @mathieuboudreau and @agahkarakuzu -- will update the manuscrpt and resubmit when i find 5min

**Comment by jcohenadad** [comment] 2024-05-28 17:33
Fixed in https://github.com/shimming-toolbox/rf-shimming-7t/tree/r20240528

**Closed by jcohenadad** 2024-05-28 17:33 UTC
